version: '3'
services:
  app:
    build: .
    environment:
      - DD_TRACE_AGENT_PORT=8126
      - DD_TRACE_AGENT_HOSTNAME=ddagent
    ports:
      - "4000:4000"
    depends_on:
      - ddagent
      - db
    command: /app/run.sh 

  ddagent:
    container_name: ddagent
    image: datadog/agent:latest
    environment:
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_BIND_HOST=0.0.0.0
    env_file:
      - datadog.env
    ports:
      - "8126:8126/tcp"

  db:
    image: onjin/alpine-postgres:9.5
    container_name: "db"
    ports:
      - "5432:5432"

